from twilio.rest import Client

account_SID = 'ACccac549d1a3a9a3be8488c0cb4b54663'          #Account SID of Twilio account
auth_token = '2024fde18ac093609b42daaaf61c2853'             #Authentication token generated by Twilio
client = Client(account_SID, auth_token)

message = client.messages \
                .create(
                     body="This message is python generated.....",
                     from_='+18622596759',      #Number used to send sms genreated by Twilio
                     to='+917483093700'         #Phone number to which the sms has to be sent
                 )

print(message.sid)